services:
  mysql:
    image: mysql:8.4
    container_name: my-im-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: im_demo
    ports:
      - "3307:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7.4
    container_name: my-im-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: my-im-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: im
      RABBITMQ_DEFAULT_PASS: im
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:
